/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.levi.phraseinator;

public class App {
    public static void main(String[] args) {
       
        System.out.println( new Phraseinator().generate());
        System.out.println( new Phraseinator().generate2());
        System.out.println( new Phraseinator().generate2());
        System.out.println( new Phraseinator().generate2());
        System.out.println( new Phraseinator().generate2());
        System.out.println( new Phraseinator().generate2());
        System.out.println( new Phraseinator().generate2());
        System.out.println( new Phraseinator().generate2());
    }       
}
